project_id = "owxuoejwnxspzuleeyqi"

[functions.send-follow-up]
verify_jwt = false

[functions.generate-followup]
verify_jwt = false

[functions.digital-clone-chat]
verify_jwt = false

[functions.verify-site-password]
verify_jwt = false

[functions.verify-user-password]
verify_jwt = false
